version: "3.7"

services:
  api:
    container_name: tdd-node-api
    build: .
    restart: always
    env_file: 
      - .env
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    links:
      - db
    ports:
      - ${APP_PORT}:3000
    command: 'npm install && npm start'

  db:
    image: mysql:5.7
    container_name: docker-node-mysql
    restart: always
    env_file: 
      - .env
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    ports: 
      - ${DB_PORT}:3306
    volumes: 
      - dbdata-volume:/data/db
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      
volumes:
  dbdata-volume: