version: "3"

services:
  api:
    build: .
    container_name: tdd-node-api
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      
  db:
    image: mysql:5.7.31
    container_name: 'docker-node-mysql'
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3308:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=America/Sao_Paulo
      